//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.06 at 08:29:47 PM MSK 
//


package ru.nuyanzin.xml.agents;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.nuyanzin.xml.agents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Agents_QNAME = new QName("", "agents");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.nuyanzin.xml.agents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AgentsType }
     * 
     */
    public AgentsType createAgentsType() {
        return new AgentsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "agents")
    public JAXBElement<AgentsType> createAgents(AgentsType value) {
        return new JAXBElement<AgentsType>(_Agents_QNAME, AgentsType.class, null, value);
    }

}
